module.exports = {
  GET_CONTRACT_BY_PROVIDER: " GET_CONTRACT_BY_PROVIDER",
  GET_CONTRACT_BY_SIGNER: " GET_CONTRACT_BY_SIGNER",
  SET_PROVIDER: "SET_PROVIDER",
  SET_SIGNER: "SET_SIGNER",
  SET_METAMASK_ENABLED: "SET_METAMASK_ENABLED",
  SET_CHAIN_ID: "SET_CHAIN_ID",
};
